name: Nightly ETL
on:
  schedule:
    - cron: '10 1 * * *'  # 01:10 America/Toronto
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install deps
        run: npm ci || true
      - name: Run ETL
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          META_TOKEN: ${{ secrets.META_TOKEN }}
          TIKTOK_TOKEN: ${{ secrets.TIKTOK_TOKEN }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
          TZ: America/Toronto
        run: node scripts/etl/compute_metrics.ts --cron
