name: Nightly ETL
on:
  schedule:
    - cron: '10 1 * * *'  # 01:10 America/Toronto
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Install deps
        run: npm ci || true
      - name: Run ETL
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          META_TOKEN: ${{ secrets.META_TOKEN }}
          META_ACCOUNT_ID: ${{ secrets.META_ACCOUNT_ID }}
          TIKTOK_TOKEN: ${{ secrets.TIKTOK_TOKEN }}
          TIKTOK_ADVERTISER_ID: ${{ secrets.TIKTOK_ADVERTISER_ID }}
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          TZ: America/Toronto
        run: node scripts/etl/compute_metrics.ts --cron
