name: Preflight Checks

on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm ci || true
      
      - name: Run preflight checks
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          TZ: America/Toronto
        run: tsx scripts/agents/preflight.ts
      
      - name: Upload preflight report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: preflight-report
          path: reports/exec/preflight_report.md
