const fs=require('fs');
const plan=[
  {area:'perf',item:'Edge runtime for light APIs',action:'set runtime="edge" where safe',impact:'latency↓'},
  {area:'security',item:'Validate inputs & typed JSON',action:'zod/yup guards',impact:'risk↓'},
  {area:'db',item:'Split CONCURRENT indexes from TX',action:'standalone online-safe migrations',impact:'locks↓'},
  {area:'ux',item:'Route-level code-splitting',action:'dynamic imports',impact:'LCP↓'}
];
fs.writeFileSync('docs/architecture/03_optimization_plan.md','# Optimization Plan\n\n'+plan.map(p=>`- **${p.area}** — ${p.item} → ${p.action} _(impact: ${p.impact})_`).join('\n')+'\n');
fs.writeFileSync('patches/preview/example.patch.txt','// [META-AUDIT:SUGGESTION]\n// Consider setting runtime="edge" for light API routes; add zod validation + rate-limit.');
fs.writeFileSync('docs/architecture/04_pr_summary.md','# PR Summary\n\nAuto-generated by Meta-Architect Audit.\n');
fs.writeFileSync('docs/architecture/rollback.sh','#!/usr/bin/env bash\nset -euo pipefail\necho "Reverting Meta-Architect changes in this PR…"\n');
fs.chmodSync('docs/architecture/rollback.sh',0o755);
