#!/usr/bin/env bash
# Reads ISSUE_REGISTER.json and opens one PR per unresolved issue with a matching fix script.
# Requires: gh CLI, GITHUB_TOKEN env (provided by GitHub Actions automatically).
set -euo pipefail
ROOT="${1:-.}"
REG="$ROOT/docs/audit_investor_suite/ISSUE_REGISTER.json"
[ -f "$REG" ] || { echo "No ISSUE_REGISTER.json found."; exit 0; }
command -v jq >/dev/null || { echo "jq is required"; exit 1; }
command -v gh >/dev/null || { echo "gh CLI required"; exit 1; }

gh auth status || gh auth login --with-token <<<"${GITHUB_TOKEN:-}"

mapfile -t ISSUES < <(jq -c '.issues[] | select(.status!="resolved")' "$REG")
for I in "${ISSUES[@]}"; do
  id=$(jq -r '.id' <<<"$I")
  slug=$(jq -r '.slug' <<<"$I" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9-' '-')
  severity=$(jq -r '.severity' <<<"$I")
  title=$(jq -r '.title' <<<"$I")
  domain=$(jq -r '.domain' <<<"$I")
  script_path="infra/fixes/fix_${slug}.sh"
  [ -f "$script_path" ] || script_path="infra/fixes/fix_${slug}.mjs"
  [ -f "$script_path" ] || script_path="infra/fixes/fix_${slug}.py"

  if [ ! -f "$script_path" ]; then
    echo "No fix script for $slug; skipping."
    continue
  fi

  branch="fix/${slug}"
  echo "==> Creating branch: $branch"
  git checkout -b "$branch" || git checkout "$branch"

  # Apply fix and stage changes.
  infra/fixes/_apply_and_stage.sh "$script_path"

  # Commit with structured message.
  msg="fix($domain): ${title} [${severity}] (#${id})"
  git commit -m "$msg" || echo "No changes to commit for $slug"

  # Push branch and open PR if there are commits ahead.
  git push -u origin "$branch" || true
  # Create PR if none exists
  if ! gh pr list --head "$branch" --state open --json number | jq -e 'length>0' >/dev/null; then
    gh pr create \
      --title "$msg" \
      --body "Automated remediation for **${title}**\n\n- Issue: ${id}\n- Domain: ${domain}\n- Severity: ${severity}\n\nThis PR was generated by the Remediation Orchestrator. Please review carefully.\n" \
      --base "${GITHUB_BASE_REF:-main}" || \
    gh pr create \
      --title "$msg" \
      --body "Automated remediation for **${title}**\n\n- Issue: ${id}\n- Domain: ${domain}\n- Severity: ${severity}\n\nThis PR was generated by the Remediation Orchestrator. Please review carefully.\n"
  fi

  # Return to default branch to continue loop
  git checkout - || git checkout "${GITHUB_BASE_REF:-main}" || true
done
