#!/bin/bash
# Cleanup script to archive redundant completion/summary files
# Run with: bash scripts/cleanup_redundant_files.sh

set -e

ARCHIVE_DIR="docs/archive/completion_summaries"
mkdir -p "$ARCHIVE_DIR"

# List of redundant completion files to archive (keep essential ones)
REDUNDANT_FILES=(
  "ADDITIONAL_FEATURES_COMPLETE.md"
  "ADDITIONAL_IMPROVEMENTS_COMPLETE.md"
  "ALL_ENHANCEMENTS_COMPLETE.md"
  "ALL_NEXT_STEPS_COMPLETE.md"
  "ALL_OPTIMIZATIONS_COMPLETE.md"
  "ALL_WAVES_COMPLETE.md"
  "AUTONOMOUS_ENGINE_COMPLETE.md"
  "AUTONOMOUS_ENGINE_IMPLEMENTATION.md"
  "AUTONOMOUS_ENGINE_SUMMARY.md"
  "AI_FEATURES_COMPLETE.md"
  "COMPLETE_IMPLEMENTATION_STATUS.md"
  "COMPLETE_IMPLEMENTATION_SUMMARY.md"
  "COMPLETE_OPERATIONAL_ALIGNMENT.md"
  "COMPLETE_PSYCHOLOGY_IMPLEMENTATION.md"
  "COMPLETE_SETUP_SUMMARY.md"
  "COMPREHENSIVE_ENHANCEMENTS_SUMMARY.md"
  "CONFIGURATION_AND_TESTING_COMPLETE.md"
  "CONTINUITY_AUDIT_SUMMARY.md"
  "DEPENDENCIES_ROUTES_COMPLETE.md"
  "ENHANCEMENTS_COMPLETE.md"
  "ENVIRONMENT_SETUP_COMPLETE.md"
  "FINAL_DEPENDENCY_ROUTE_REPORT.md"
  "FINAL_IMPLEMENTATION_SUMMARY.md"
  "FINAL_SUMMARY.md"
  "IMPLEMENTATION_COMPLETE_SUMMARY.md"
  "IMPLEMENTATION_COMPLETE.md"
  "INTEGRATION_COMPLETE.md"
  "INTEGRATIONS_COMPLETE.md"
  "ML_IMPLEMENTATION_COMPLETE.md"
  "MONTH1_COMPLETION.md"
  "MONTH2_AND_3_COMPLETION.md"
  "MONTH5_AND_6_COMPLETION.md"
  "NEXT_STEPS_IMPLEMENTATION_COMPLETE.md"
  "OPERATIONAL_EXCELLENCE_COMPLETE.md"
  "P1_COMPLETION_SUMMARY.md"
  "PHASE_1_4_COMPLETION_SUMMARY.md"
  "SPRINT_COMPLETION_SUMMARY.md"
  "ROADMAP_COMPLETION_SUMMARY.md"
  "REFACTORING_COMPLETE.md"
  "REMAINING_OPTIMIZATIONS_COMPLETE.md"
  "SYSTEMS_OPTIMIZATION_COMPLETE.md"
  "VERCEL_HARDENING_IMPLEMENTATION_SUMMARY.md"
  "TRUST_IMPLEMENTATION_SUMMARY.md"
  "PWA_COMPLETION_CHECKLIST.md"
)

echo "Archiving redundant completion files..."

for file in "${REDUNDANT_FILES[@]}"; do
  if [ -f "$file" ]; then
    echo "Archiving: $file"
    mv "$file" "$ARCHIVE_DIR/"
  fi
done

echo "✅ Archived ${#REDUNDANT_FILES[@]} files to $ARCHIVE_DIR"
echo ""
echo "Essential files kept:"
echo "  - MASTER_ONE_SHOT_COMPLETE.md"
echo "  - ALL_ACTIONS_COMPLETE.md"
echo "  - COMPLETION_CHECKLIST.md"
echo "  - EXECUTION_GUIDE.md"
echo "  - QUICK_START.md"
echo "  - PRIORITY_ACTIONS_SUMMARY.md"
