#!/usr/bin/env tsx
/**
 * Monitoring Dashboard Generator
 * 
 * Generates monitoring dashboards and alerting configurations for:
 * - Application performance
 * - Error rates
 * - API latency
 * - Database performance
 * - Cost metrics
 */

import { writeFileSync } from 'fs'
import { join } from 'path'

interface MonitoringDashboard {
  name: string
  description: string
  metrics: Array<{
    name: string
    query: string
    threshold?: {
      warning: number
      error: number
    }
  }>
  alerts: Array<{
    name: string
    condition: string
    severity: 'warning' | 'error' | 'critical'
  }>
}

const DASHBOARDS: SecretDashboard[] = [
  {
    name: 'Application Performance',
    description: 'Core application performance metrics',
    metrics: [
      {
        name: 'API Response Time (p95)',
        query: 'histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))',
        threshold: {
          warning: 500,
          error: 1000,
        },
      },
      {
        name: 'Error Rate',
        query: 'rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])',
        threshold: {
          warning: 0.01, // 1%
          error: 0.05, // 5%
        },
      },
      {
        name: 'Request Rate',
        query: 'rate(http_requests_total[5m])',
      },
    ],
    alerts: [
      {
        name: 'High API Latency',
        condition: 'p95_latency > 1000ms for 5 minutes',
        severity: 'error',
      },
      {
        name: 'High Error Rate',
        condition: 'error_rate > 5% for 5 minutes',
        severity: 'critical',
      },
    ],
  },
  {
    name: 'Database Performance',
    description: 'Database query performance and health',
    metrics: [
      {
        name: 'Query Duration (p95)',
        query: 'histogram_quantile(0.95, rate(db_query_duration_seconds_bucket[5m]))',
        threshold: {
          warning: 200,
          error: 500,
        },
      },
      {
        name: 'Connection Pool Usage',
        query: 'db_connection_pool_active / db_connection_pool_max',
        threshold: {
          warning: 0.8, // 80%
          error: 0.95, // 95%
        },
      },
      {
        name: 'Slow Queries',
        query: 'rate(db_slow_queries_total[5m])',
        threshold: {
          warning: 10,
          error: 50,
        },
      },
    ],
    alerts: [
      {
        name: 'Slow Database Queries',
        condition: 'slow_queries > 50/min for 5 minutes',
        severity: 'warning',
      },
      {
        name: 'Connection Pool Exhausted',
        condition: 'pool_usage > 95% for 2 minutes',
        severity: 'critical',
      },
    ],
  },
  {
    name: 'Cost Metrics',
    description: 'Infrastructure and service costs',
    metrics: [
      {
        name: 'Supabase Database Size',
        query: 'supabase_database_size_bytes',
      },
      {
        name: 'Supabase Bandwidth',
        query: 'rate(supabase_bandwidth_bytes[1h])',
      },
      {
        name: 'Vercel Function Invocations',
        query: 'rate(vercel_function_invocations_total[1h])',
      },
    ],
    alerts: [
      {
        name: 'High Database Usage',
        condition: 'database_size > 7GB',
        severity: 'warning',
      },
      {
        name: 'Bandwidth Limit Approaching',
        condition: 'bandwidth > 45GB/month',
        severity: 'warning',
      },
    ],
  },
]

function generatePrometheusConfig(): string {
  return `# Prometheus Alerting Rules
# Generated by monitoring-dashboard.ts

groups:
  - name: application_alerts
    interval: 1m
    rules:
      - alert: HighAPILatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: error
        annotations:
          summary: "High API latency detected"
          description: "P95 latency is {{ $value }}s (threshold: 1s)"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} (threshold: 5%)"

  - name: database_alerts
    interval: 1m
    rules:
      - alert: SlowDatabaseQueries
        expr: rate(db_slow_queries_total[5m]) > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries detected"
          description: "{{ $value }} slow queries per minute"

      - alert: ConnectionPoolExhausted
        expr: db_connection_pool_active / db_connection_pool_max > 0.95
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Connection pool nearly exhausted"
          description: "{{ $value | humanizePercentage }} of connections in use"

  - name: cost_alerts
    interval: 1h
    rules:
      - alert: HighDatabaseUsage
        expr: supabase_database_size_bytes > 7516192768  # 7GB
        labels:
          severity: warning
        annotations:
          summary: "Database size approaching limit"
          description: "Database size is {{ $value | humanizeBytes }}"

      - alert: BandwidthLimitApproaching
        expr: rate(supabase_bandwidth_bytes[1h]) * 720 > 48318382080  # 45GB/month
        labels:
          severity: warning
        annotations:
          summary: "Bandwidth limit approaching"
          description: "Projected monthly bandwidth: {{ $value | humanizeBytes }}"
`
}

function generateGrafanaDashboard(): string {
  return JSON.stringify({
    dashboard: {
      title: 'Floyo Monitoring Dashboard',
      tags: ['floyo', 'monitoring'],
      timezone: 'browser',
      panels: [
        {
          title: 'API Response Time (p95)',
          type: 'graph',
          targets: [
            {
              expr: 'histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))',
            },
          ],
        },
        {
          title: 'Error Rate',
          type: 'graph',
          targets: [
            {
              expr: 'rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])',
            },
          ],
        },
        {
          title: 'Database Query Duration',
          type: 'graph',
          targets: [
            {
              expr: 'histogram_quantile(0.95, rate(db_query_duration_seconds_bucket[5m]))',
            },
          ],
        },
        {
          title: 'Connection Pool Usage',
          type: 'gauge',
          targets: [
            {
              expr: 'db_connection_pool_active / db_connection_pool_max',
            },
          ],
        },
      ],
    },
  }, null, 2)
}

function main() {
  console.log('📊 Generating Monitoring Dashboards\n')
  
  // Generate Prometheus alerting rules
  const prometheusConfig = generatePrometheusConfig()
  writeFileSync(join(process.cwd(), 'monitoring/prometheus-alerts.yml'), prometheusConfig)
  console.log('✅ Generated Prometheus alerting rules')
  
  // Generate Grafana dashboard
  const grafanaDashboard = generateGrafanaDashboard()
  writeFileSync(join(process.cwd(), 'monitoring/grafana-dashboard.json'), grafanaDashboard)
  console.log('✅ Generated Grafana dashboard')
  
  // Generate monitoring documentation
  const monitoringDoc = `# Monitoring Dashboards

## Available Dashboards

${DASHBOARDS.map(d => `### ${d.name}\n\n${d.description}\n\n**Metrics:**\n${d.metrics.map(m => `- ${m.name}`).join('\n')}\n\n**Alerts:**\n${d.alerts.map(a => `- ${a.name} (${a.severity}): ${a.condition}`).join('\n')}\n`).join('\n')}

## Setup

1. **Prometheus**: Import \`monitoring/prometheus-alerts.yml\`
2. **Grafana**: Import \`monitoring/grafana-dashboard.json\`
3. **Alerting**: Configure alertmanager with Prometheus rules

## Metrics Collection

Metrics are collected via:
- Sentry (errors, performance)
- PostHog (analytics)
- Custom instrumentation (API latency, DB queries)
`
  
  writeFileSync(join(process.cwd(), 'docs/monitoring-dashboards.md'), monitoringDoc)
  console.log('✅ Generated monitoring documentation')
  
  console.log('\n✅ Monitoring dashboards generated successfully!')
}

if (require.main === module) {
  main()
}

export { generatePrometheusConfig, generateGrafanaDashboard }
