/**
 * Documentation & Knowledge Agent
 * Auto-updates README, CHANGELOG, and architecture docs
 */

import { writeFileSync, existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';
import type { RepoContext } from './repo-context.js';

export interface DocumentationUpdate {
  timestamp: string;
  filesUpdated: string[];
  intentLog: Array<{
    commit: string;
    message: string;
    timestamp: string;
    intent: string;
  }>;
}

export class DocumentationAgent {
  private workspacePath: string;
  private intentLogPath: string;

  constructor(workspacePath: string = process.cwd()) {
    this.workspacePath = workspacePath;
    this.intentLogPath = join(workspacePath, 'docs', 'intent-log.md');
  }

  /**
   * Update documentation based on recent changes
   */
  async updateDocumentation(context: RepoContext): Promise<DocumentationUpdate> {
    const update: DocumentationUpdate = {
      timestamp: new Date().toISOString(),
      filesUpdated: [],
      intentLog: [],
    };

    // Extract recent commits for intent log
    await this.updateIntentLog(update);

    // Update CHANGELOG
    await this.updateChangelog(update);

    // Update architecture docs if needed
    await this.updateArchitectureDocs(update, context);

    return update;
  }

  /**
   * Update intent log from recent commits
   */
  private async updateIntentLog(update: DocumentationUpdate): Promise<void> {
    try {
      // Get recent commits (last 10)
      const commits = execSync('git log --pretty=format:"%H|%s|%ai" -10', {
        encoding: 'utf-8',
        cwd: this.workspacePath,
      }).trim();

      if (!commits) {
        return;
      }

      // Ensure docs directory exists
      const docsDir = join(this.workspacePath, 'docs');
      if (!existsSync(docsDir)) {
        require('fs').mkdirSync(docsDir, { recursive: true });
      }

      // Check if intent log exists
      const existingLog = existsSync(this.intentLogPath)
        ? readFileSync(this.intentLogPath, 'utf-8')
        : '# Intent Log\n\nCommit reasoning trail for autonomous improvements.\n\n';

      // Parse commits
      const lines = commits.split('\n');
      for (const line of lines) {
        const [hash, message, date] = line.split('|');
        
        // Check if already logged
        if (!existingLog.includes(hash.substring(0, 8))) {
          update.intentLog.push({
            commit: hash.substring(0, 8),
            message,
            timestamp: date,
            intent: this.extractIntent(message),
          });
        }
      }

      // Append new entries
      if (update.intentLog.length > 0) {
        let logContent = existingLog;
        if (!logContent.endsWith('\n')) {
          logContent += '\n';
        }

        for (const entry of update.intentLog) {
          logContent += `\n## ${entry.commit} - ${entry.timestamp}\n\n`;
          logContent += `**Message**: ${entry.message}\n\n`;
          logContent += `**Intent**: ${entry.intent}\n\n`;
        }

        writeFileSync(this.intentLogPath, logContent, 'utf-8');
        update.filesUpdated.push('docs/intent-log.md');
      }
    } catch (e) {
      // Git might not be available or not a git repo
      console.warn('Could not update intent log:', e);
    }
  }

  /**
   * Update CHANGELOG
   */
  private async updateChangelog(update: DocumentationUpdate): Promise<void> {
    const changelogPath = join(this.workspacePath, 'CHANGELOG.md');
    
    // Check if CHANGELOG exists
    if (!existsSync(changelogPath)) {
      // Create initial CHANGELOG
      const initialContent = `# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Added
- Initial changelog

---
*Auto-generated by Unified Agent System*
`;

      writeFileSync(changelogPath, initialContent, 'utf-8');
      update.filesUpdated.push('CHANGELOG.md');
    }
  }

  /**
   * Update architecture documentation
   */
  private async updateArchitectureDocs(
    update: DocumentationUpdate,
    context: RepoContext
  ): Promise<void> {
    const archPath = join(this.workspacePath, 'docs', 'architecture.md');
    
    // Create or update architecture doc
    if (!existsSync(archPath)) {
      const archContent = this.generateArchitectureDoc(context);
      const docsDir = join(this.workspacePath, 'docs');
      if (!existsSync(docsDir)) {
        require('fs').mkdirSync(docsDir, { recursive: true });
      }
      writeFileSync(archPath, archContent, 'utf-8');
      update.filesUpdated.push('docs/architecture.md');
    }
  }

  /**
   * Generate architecture documentation
   */
  private generateArchitectureDoc(context: RepoContext): string {
    return `# Architecture Documentation

Generated: ${new Date().toISOString()}

## Repository Type
- **Type**: ${context.type}
- **Operating Modes**: ${context.modes.join(', ')}

## Technology Stack

### Frameworks
${context.frameworks.map((f) => `- ${f}`).join('\n')}

### Package Manager
- ${context.packageManager}

### Databases
${context.databases.map((d) => `- ${d}`).join('\n')}

### Cloud Providers
${context.cloudProviders.map((c) => `- ${c}`).join('\n')}

## Project Structure
- Frontend: ${context.hasFrontend ? 'Yes' : 'No'}
- Backend: ${context.hasBackend ? 'Yes' : 'No'}
- Mobile: ${context.hasMobile ? 'Yes' : 'No'}

---
*Auto-generated by Unified Agent System*
`;
  }

  /**
   * Extract intent from commit message
   */
  private extractIntent(message: string): string {
    // Simple intent extraction
    const lower = message.toLowerCase();
    
    if (lower.includes('fix') || lower.includes('bug')) {
      return 'Bug fix';
    } else if (lower.includes('feat') || lower.includes('add')) {
      return 'Feature addition';
    } else if (lower.includes('refactor')) {
      return 'Code refactoring';
    } else if (lower.includes('perf') || lower.includes('optimize')) {
      return 'Performance optimization';
    } else if (lower.includes('docs')) {
      return 'Documentation update';
    } else if (lower.includes('test')) {
      return 'Test addition/update';
    } else if (lower.includes('security') || lower.includes('sec')) {
      return 'Security improvement';
    } else {
      return 'General update';
    }
  }
}
