#!/usr/bin/env tsx
/**
 * System Doctor
 * Self-healing agent that detects drift and opens tickets
 */

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { logger } from '../lib/logger.js';
import { verifyDatabase } from './verify_db.js';
import { generateDeltaMigration } from './generate_delta_migration.js';
import { notify } from './notify.js';

interface SystemIssue {
    component: string;
    issue: string;
    severity: 'low' | 'medium' | 'high' | 'critical';
    fix: string;
    owner?: string;
}

async function checkDeltaMigration(): Promise<SystemIssue[]> {
    const issues: SystemIssue[] = [];
    
    try {
        logger.info('Checking for missing database objects...');
        await generateDeltaMigration();
        
        // Check if delta migration was generated
        const migrationsDir = path.join(process.cwd(), 'supabase', 'migrations');
        const files = fs.readdirSync(migrationsDir);
        const deltaFiles = files.filter(f => f.includes('_delta.sql'));
        
        if (deltaFiles.length > 0) {
            const latestDelta = deltaFiles.sort().reverse()[0];
            issues.push({
                component: 'database',
                issue: `Delta migration generated: ${latestDelta}`,
                severity: 'medium',
                fix: `Run: supabase db push or apply migration ${latestDelta}`,
            });
        }
    } catch (error) {
        issues.push({
            component: 'delta_migration',
            issue: `Failed to generate delta migration: ${error instanceof Error ? error.message : String(error)}`,
            severity: 'high',
            fix: 'Check database connection and migration script',
        });
    }
    
    return issues;
}

async function checkDatabaseVerification(): Promise<SystemIssue[]> {
    const issues: SystemIssue[] = [];
    
    try {
        const verified = await verifyDatabase();
        if (!verified) {
            issues.push({
                component: 'database',
                issue: 'Database verification failed',
                severity: 'critical',
                fix: 'Run verify_db.ts to see specific failures',
            });
        }
    } catch (error) {
        issues.push({
            component: 'database',
            issue: `Database verification error: ${error instanceof Error ? error.message : String(error)}`,
            severity: 'critical',
            fix: 'Check database connection and schema',
        });
    }
    
    return issues;
}

async function applyDeltaMigration(): Promise<boolean> {
    try {
        logger.info('Attempting to apply delta migration...');
        
        // Try Supabase CLI first
        try {
            execSync('supabase db push --include-all', { stdio: 'inherit' });
            return true;
        } catch (error) {
            logger.warn('Supabase CLI failed, trying psql fallback...');
            
            // Fallback to psql per-file
            const migrationsDir = path.join(process.cwd(), 'supabase', 'migrations');
            const files = fs.readdirSync(migrationsDir)
                .filter(f => f.includes('_delta.sql'))
                .sort();
            
            if (files.length > 0) {
                const dbUrl = process.env.SUPABASE_DB_URL || process.env.DATABASE_URL;
                if (!dbUrl) {
                    throw new Error('Missing database URL');
                }
                
                const latestDelta = files[files.length - 1];
                const sqlFile = path.join(migrationsDir, latestDelta);
                const sql = fs.readFileSync(sqlFile, 'utf-8');
                
                // Apply via psql
                execSync(`psql "${dbUrl}" -f "${sqlFile}"`, { stdio: 'inherit' });
                return true;
            }
            
            return false;
        }
    } catch (error) {
        logger.error('Failed to apply delta migration:', error);
        return false;
    }
}

async function createTicket(issue: SystemIssue): Promise<void> {
    const backlogDir = path.join(process.cwd(), 'backlog');
    fs.mkdirSync(backlogDir, { recursive: true });
    
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').split('T')[0];
    const ticketFile = path.join(backlogDir, `READY_system_fix_${timestamp}_${issue.component}.md`);
    
    const ticket = `# READY: System Fix - ${issue.component}

**Priority:** ${issue.severity === 'critical' ? 'P0' : issue.severity === 'high' ? 'P1' : 'P2'}  
**Owner:** ${issue.owner || 'Engineering'}  
**Status:** Ready  
**Severity:** ${issue.severity.toUpperCase()}

## Issue

${issue.issue}

## Fix

${issue.fix}

## Detection

- **Detected by:** System Doctor
- **Timestamp:** ${new Date().toISOString()}
- **Component:** ${issue.component}

## Acceptance Criteria

- [ ] Issue resolved
- [ ] Verification passes
- [ ] System health restored

## Notes

Auto-generated by system_doctor.ts
`;

    fs.writeFileSync(ticketFile, ticket);
    logger.info(`Created ticket: ${ticketFile}`);
}

async function main() {
    const startTime = Date.now();
    logger.info('System Doctor: Starting health check...');

    const allIssues: SystemIssue[] = [];

    // Check delta migration
    const deltaIssues = await checkDeltaMigration();
    allIssues.push(...deltaIssues);

    // Check database verification
    const dbIssues = await checkDatabaseVerification();
    allIssues.push(...dbIssues);

    // If delta migration needed, try to apply it
    if (deltaIssues.some(i => i.component === 'database' && i.issue.includes('Delta migration'))) {
        logger.info('Attempting to auto-heal: applying delta migration...');
        const applied = await applyDeltaMigration();
        
        if (applied) {
            // Re-verify after applying
            const recheckIssues = await checkDatabaseVerification();
            if (recheckIssues.length === 0) {
                logger.info('✅ Auto-healed: Delta migration applied successfully');
                await notify({
                    title: 'System Auto-Healed',
                    message: 'Delta migration applied and verified successfully',
                    status: 'success',
                });
                return;
            }
        }
    }

    // Create tickets for unresolved issues
    const criticalIssues = allIssues.filter(i => i.severity === 'critical' || i.severity === 'high');
    
    if (criticalIssues.length > 0) {
        logger.error(`Found ${criticalIssues.length} critical/high severity issues`);
        
        for (const issue of criticalIssues) {
            await createTicket(issue);
        }

        await notify({
            title: 'System Doctor: Issues Detected',
            message: `Found ${criticalIssues.length} critical/high issues. Tickets created in backlog.`,
            status: 'error',
            fields: criticalIssues.map(i => ({
                name: i.component,
                value: i.issue,
            })),
        });

        process.exit(1);
    }

    const duration = ((Date.now() - startTime) / 1000).toFixed(2);
    logger.info(`System Doctor completed in ${duration}s - System healthy`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
    main();
}

export { checkDeltaMigration, checkDatabaseVerification, createTicket };
